slogan: “你所热爱的，就是你的生活！”
email: johnming143@outlook.com
logo: "/images/logo.svg"

mathjax: true # 加载 LateX 数学公式库

favicon: # 配置网页图标
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: page1 # 文章的分类（category）名，如 developer
      path: # 若不设置则默认使用 name
      title: 自我介绍 # 菜单名，如 开发者
      icon: /images/icon/icon-code.svg # 图标的路径
      description: # 描述
    - name: page2 # 文章的分类（category）名，如 developer
      path: # 若不设置则默认使用 name
      title: 子页二 # 菜单名，如 开发者
      icon: /images/icon/icon-pi.svg # 图标的路径
      description: # 描述

index: # 配置首页个性化内容
  motto: "应无所住 而生其心"
  poem:
    - 君不见高堂明镜悲白发
    - 朝如青丝暮成雪
  photo: /images/hello.jpg
  about:
    title: 关于
    text:
      - 致未来或过去，致思想是自由的、人们相互各异而且并非孤独生活着的时代
      -
      - 致事实存在不变、发生过就不会被清除的时代： 
      -
      - 从一个千篇一律的时代，从一个孤独的时代，从老大哥的时代，从双重思想的时代——向悠致意！

foot:
  title:
    - "海内存知己"
    - "天涯若比邻"

links: # 朋友
  - name: "nofated"
    url: https://blog.nofated.win

social: # 账号
  - name: "github"
    icon: "/images/logo-github.svg"
    url: https://github.com/JohnMing143
  - name: "虚位以待"
    icon: ""
    url: 
  - name: "telegram"
    icon: "/images/telegram.png"
    url: https://t.me/xiaoming1314521

reward: # 赞赏
  enable: true
  face: "/images/head.jpg" # 头像图片
  paycode: "/images/pay.jpg" # 支付码图片
  text: “请作者喝杯咖啡”
  btnText: 喜欢作者

# see https://github.com/gitalk/gitalk
gitalk: # gitalk 评论
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: false
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

custom_font:
  name: "SourceHanSerifCN"
  extName: "ttf"
  folder: "font/SourceHanSerifCN/"
  subFamily:
    - regular.ttf
    - bold.ttf
  targetPath: "font/"
